version: "3.9"

services:

python:
  image: python:3.9
  ports:
    - "8000:8000"
  volumes:
    - ./app:/app
  environment:
    - PYTHON_UNBUFFERED=1

node.js:
  image: node.js:19.8.1
  ports: 
    - "30000-32767"
  volumes:
    - ./app:/app
  environment:
   - NODE.JS_UNBUFFERED=1

  
php:
  image: php:8.2
  ports:
    - "80:443"
  volumes:
    - ./app:/app
  environment:
    - PHP_UNBUFFERED=1

